   
   -- DDL
CREATE TABLE doctors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50)
);


CREATE TABLE ROOMS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR2(20)

);

CREATE TABLE patients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(20),
    last_name VARCHAR2(20),
    doctors_id NUMBER,
    room_id NUMBER,
    CONSTRAINT fk_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT fk_room FOREIGN KEY (room_id) REFERENCES rooms(id)

);

CREATE TABLE medecines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(20)
);

CREATE TABLE patientMedecine (
    patient_id NUMBER,
    medecine_id NUMBER,
    CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_medecine FOREIGN KEY (medecine_id) REFERENCES medecines(id)
    
);


--DML

-- Insert Data
INSERT INTO medecines (name) VALUES  (1, 'Ibuprofen');
INSERT INTO patientMedecine (patient_id, medecine_id) VALUES (2, 1);
INSERT INTO doctors(first_name,last_name) VALUES ('jeff', 'smith');
INSERT INTO rooms (room_number) VALUES ('B102');
INSERT INTO patients (first_name,last_name,doctor_id,room_id) VALUES ('peter','manzi',2,4);


-- Update Data
UPDATE doctors SET first_name = 'smith' WHERE room_number = B102;

-- Delete Data
DELETE FROM DOCTORS WHERE doctor first_name = jeff;


-- Granting Privileges (DCL)

GRANT SELECT, INSERT ON doctors TO user_name;

-- TCL commands 
savepoint beforedelete;
Delete from patients where id =22;
select * from patients;
rollback to savepoint beforedelete;
select * from patients;


--TO SELECT
SELECT * FROM doctors;

-- TO INSERT
INSERT INTO rooms (room_number) VALUES (B209);


-- TO DELETE
DELETE FROM rooms WHERE room_number = B209 ;


--  to perform Subquery 
SELECT last_name from doctors where id IN (select doctor_id from patients where doctor_id =21);

-- JOINS
select p.first_name || ' ' || p.last_name as fullname, D.first_name || ' '|| D.last_name AS doctors, R.room_number AS ROOMS FROM PATIENTS P JOIN DOCTORS D ON P.doctor_id=D.ID JOIN ROOMS R ON P.room_id= R.ID;
